service: mortgage.serverless

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  stage: ${opt:stage, 'local'}          # Set the default stage used. Default is dev
  region: ${opt:region, 'eu-west-1'}    # Overwrite the default region used. Default is eu-west-1
  stackName: tud.mortgage.stack
  runtime: nodejs10.x
  environment:
    MORTGAGE_DB_TABLE: ${self:service}.${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.MORTGAGE_DB_TABLE}"

# Custom Variables
custom:
  stages:
    - local
    - dev
    - prod
  mysqlHost:
    local: localhost
    dev: devdb.example.com
    prod: ${ssm:/myapp/prod/mysql-host}
  mysqlUser:
    local: root
    dev: myapp_devuser
    prod: myapp

functions:
  create:
    handler: mortgage/create.create
    events:
      - http:
          path: mortgage
          method: post
          cors: true

  list:
    handler: mortgage/list.list
    events:
      - http:
          path: mortgage
          method: get
          cors: true

  get:
    handler: mortgage/get.get
    events:
      - http:
          path: mortgage/{id}
          method: get
          cors: true

  update:
    handler: mortgage/update.update
    events:
      - http:
          path: mortgage/{id}
          method: put
          cors: true

  delete:
    handler: mortgage/delete.delete
    events:
      - http:
          path: mortgage/{id}
          method: delete
          cors: true

resources:
  Resources:
    TUDMortagesDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.MORTGAGE_DB_TABLE}