AWSTemplateFormatVersion: 2010-09-09

Parameters: 
  DeploymentStage: 
    Type: String
    Default: "DEV"


Resources:
    IDGenTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "ID_GEN_TABLE"
        AttributeDefinitions:
          - AttributeName: idName
            AttributeType: S
        KeySchema:
          - AttributeName: idName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "CUSTOMER_TABLE"
        AttributeDefinitions:
          - AttributeName: customerId
            AttributeType: S
        KeySchema:
          - AttributeName: customerId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    MortgagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "MORTGAGES_TABLE"
        AttributeDefinitions:
          - AttributeName: mortgageId
            AttributeType: S
#          - AttributeName: customerId
#            AttributeType: S
#          - AttributeName: term
#            AttributeType: N
#          - AttributeName: loanAmount
#            AttributeType: N
#          - AttributeName: salary
#            AttributeType: N
#          - AttributeName: employerName
#            AttributeType: N
#          - AttributeName: yearsInEmployment
#            AttributeType: N
          - AttributeName: mortgageStatus
            AttributeType: S
        KeySchema:
          - AttributeName: mortgageId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: MortgateStatusIndex
            KeySchema:
              - AttributeName: mortgageStatus
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        
Outputs:
    IDGenTableARN:
      Value:
         Fn::GetAtt:
          - IDGenTable
          - Arn
      Export:
        Name: IDGenTableARN
    CustomerTableARN:
      Value:
         Fn::GetAtt:
          - CustomerTable
          - Arn
      Export:
        Name: CustomerTableARN
    MortgagesTableARN:
      Value:
         Fn::GetAtt:
          - MortgagesTable
          - Arn
      Export:
        Name: MortgagesTableARN