service: mortgage-database

custom:
  stage: ${opt:stage, self:provider.stage}
  mortgageTableName: ${self:custom.stage}.MORTGAGES_TABLE
  mortgageStateTableName: ${self:custom.stage}.MORTGAGES_STATE_TABLE
  
provider:
  name: aws
  stage: dev
  region: eu-west-1

resources:
  Resources:
    MortgagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.mortgageTableName}
        AttributeDefinitions:
          - AttributeName: mortgageId
            AttributeType: S
          - AttributeName: lastName
            AttributeType: S
        KeySchema:
          - AttributeName: mortgageId
            KeyType: HASH
          - AttributeName: lastName
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
  Resources:
    MortgageStateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.mortgageStateTableName}
        AttributeDefinitions:
          - AttributeName: mortgageId
            AttributeType: S
          - AttributeName: mortgageState
            AttributeType: S
        KeySchema:
          - AttributeName: mortgageId
            KeyType: HASH
          - AttributeName: mortgageState
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
  Outputs:
    MortgagesTableARN:
      Value:
         Fn::GetAtt:
          - MortgagesTable
          - Arn
      Export:
        Name: ${self:custom.stage}-MortgagesTableARN
    MortgageStateTableARN:
      Value:
         Fn::GetAtt:
          - MortgageStateTable
          - Arn
      Export:
        Name: ${self:custom.stage}-MortgagesStateTableARN