AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Tallaght-Mortgages-App

  '
Globals:
  Function:
    Timeout: 3
Parameters:
  LambdaRoleParameter:
    Type: String
    Default: arn:aws:iam::727432808710:role/TUD.Mortgage.Lambda.Role
    Description: Enter the ARN of an applicable IAM Role for the Lambda Functions
Resources:
  GetCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ad.aws.s3.codedeploy/620d1a8b270a8e308049d6ac9cd4ab0d
      Handler: get.get
      Runtime: nodejs10.x
      Role:
        Ref: LambdaRoleParameter
      Events:
        GetCustomerEvent:
          Type: Api
          Properties:
            Path: /customer/{id}
            Method: GET
  CreateCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ad.aws.s3.codedeploy/620d1a8b270a8e308049d6ac9cd4ab0d
      Handler: create.create
      Runtime: nodejs10.x
      Role:
        Ref: LambdaRoleParameter
      Events:
        CreateCustomerEvent:
          Type: Api
          Properties:
            Path: /customer/
            Method: PUT
  UpdateCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ad.aws.s3.codedeploy/620d1a8b270a8e308049d6ac9cd4ab0d
      Handler: update.update
      Runtime: nodejs10.x
      Role:
        Ref: LambdaRoleParameter
      Events:
        UpdateCustomerEvent:
          Type: Api
          Properties:
            Path: /customer/
            Method: POST
  GetMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ad.aws.s3.codedeploy/f8780d985137f9c4ebca5152be9cfa6d
      Handler: get.get
      Runtime: nodejs10.x
      Role:
        Ref: LambdaRoleParameter
      Events:
        GetMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/{id}
            Method: GET
  CreateMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ad.aws.s3.codedeploy/f8780d985137f9c4ebca5152be9cfa6d
      Handler: create.create
      Runtime: nodejs10.x
      Role:
        Ref: LambdaRoleParameter
      Events:
        CreateMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/
            Method: PUT
  UpdateMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ad.aws.s3.codedeploy/f8780d985137f9c4ebca5152be9cfa6d
      Handler: update.update
      Runtime: nodejs10.x
      Role:
        Ref: LambdaRoleParameter
      Events:
        CreateMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/
            Method: POST
  DeleteMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ad.aws.s3.codedeploy/f8780d985137f9c4ebca5152be9cfa6d
      Handler: delete.delete
      Runtime: nodejs10.x
      Role:
        Ref: LambdaRoleParameter
      Events:
        DeleteMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/{id}
            Method: DELETE
  ListByStatusMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://ad.aws.s3.codedeploy/f8780d985137f9c4ebca5152be9cfa6d
      Handler: list.list
      Runtime: nodejs10.x
      Role:
        Ref: LambdaRoleParameter
      Events:
        ListByStatusMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/
            Method: GET
Outputs:
  MortgageApi:
    Description: API Gateway endpoint URL for Prod stage for GetMortgageFunctionRole
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mortgage/
  GetCustomerFunction:
    Description: GetCustomerFunctionARN
    Value:
      Fn::GetAtt:
      - GetCustomerFunction
      - Arn
  CreateCustomerFunction:
    Description: CreateCustomerFunctionARN
    Value:
      Fn::GetAtt:
      - CreateCustomerFunction
      - Arn
  UpdateCustomerFunction:
    Description: UpdateCustomerFunctionARN
    Value:
      Fn::GetAtt:
      - UpdateCustomerFunction
      - Arn
