AWSTemplateFormatVersion: '2010-09-09'
Description: An example template for a Step Functions state machine.
Resources:
	MyStateMachine:
	Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: Tallaght-Workflow
      DefinitionString:
        !Sub
          - |-
            {
              "StartAt": "GetMortgageApplication",
              "States": {
                "GetMortgageApplication": {
                  "Type": "Task",
                  "Resource": "${GetMorgtageFunctionArn}",
                  "ResultPath": "$.lambdaresult",
                  "Next": "GetMortgageApplicationResult"
                },
                "GetMortgageApplicationResult": {
                  "Type": "Choice",
                  "Choices": [{
                    "Variable": "$.lambdaresult.statusCode",
                    "NumericEquals": 200,
                    "Next": "UpdateStatusToInAssessmentPass"
                  }],
                  "Default": "MortgageApplicationNotFoundMessage"
                },
                "UpdateStatusToInAssessmentPass": {
                  "Type": "Pass",
                  "OutputPath": "$.lambdaresult",
                  "Next": "UpdateStatusToInAssessment"
                },
                "MortgageApplicationNotFoundMessage": {
                  "Type": "Task",
                  "Resource": "${CreateNotificationMessageFunctionArn}",
                  "Parameters": {
                    "messageType": "mortgageNotFoundMessage",
                    "mortgageId.$": "$.mortgageId"
                  },
                  "Next": "MortgageApplicationNotFoundNotify"
                },
                "MortgageApplicationNotFoundNotify": {
                  "Type": "Task",
                  "Resource": "${SendNotificationMessageFunctionArn}",
                  "ResultPath": "$.lambdaresult",
                  "End": true
                },
                "UpdateStatusToInAssessment": {
                  "Type": "Task",
                  "Parameters": {
                    "mortgage.$": "$.mortgage",
                    "newStatus": "InAssessment"
                  },
                  "Resource": "${ChangeMortgageStatusFunctionArn}",
                  "Next": "InAssessmentMessage"
                },
                "InAssessmentMessage": {
                  "Type": "Task",
                  "Resource": "${CreateNotificationMessageFunctionArn}",
                  "Parameters": {
                    "messageType": "autoAssessmentMessage",
                    "mortgage.$": "$.mortgage"
                  },
                  "ResultPath": "$.lambdaresult",
                  "Next": "InAssessmentNotify"
                },
                "InAssessmentNotify": {
                  "Type": "Task",
                  "InputPath": "$.lambdaresult",
                  "Resource": "${SendNotificationMessageFunctionArn}",
                  "ResultPath": "$.lambdaresult",
                  "Next": "AutoAssessment"
                },
                "AutoAssessment": {
                  "Type": "Task",
                  "InputPath": "$.mortgage",
                  "Resource": "${AutoAssessmentFunctionArn}",
                  "ResultPath": "$.lambdaresult",
                  "Next": "AutoAssessmentResult"
                },
                "AutoAssessmentResult": {
                  "Type": "Choice",
                  "Choices": [{
                    "Variable": "$.lambdaresult.statusCode",
                    "NumericEquals": 200,
                    "Next": "UpdateStatusToAutoApproved"
                  }],
                  "Default": "UpdateStatusToWithUnderwriter"
                },
                "UpdateStatusToAutoApproved": {
                  "Type": "Task",
                  "Parameters": {
                    "mortgage.$": "$.mortgage",
                    "newStatus": "Approved"
                  },
                  "Resource": "${ChangeMortgageStatusFunctionArn}",
                  "Next": "AutoAssessmentApprovalMessage"
                },
                "AutoAssessmentApprovalMessage": {
                  "Type": "Task",
                  "Resource": "${CreateNotificationMessageFunctionArn}",
                  "Parameters": {
                    "messageType": "autoApprovalMessage",
                    "mortgage.$": "$.mortgage"
                  },
                  "ResultPath": "$.lambdaresult",
                  "Next": "AutoAssessmentApprovalNotify"
                },
                "AutoAssessmentApprovalNotify": {
                  "Type": "Task",
                  "InputPath": "$.lambdaresult",
                  "Resource": "${SendNotificationMessageFunctionArn}",
                  "ResultPath": "$.lambdaresult",
                  "End": true
                },
                "UpdateStatusToWithUnderwriter": {
                  "Type": "Task",
                  "Parameters": {
                    "mortgage.$": "$.mortgage",
                    "newStatus": "WithUnderwriter"
                  },
                  "Resource": "${ChangeMortgageStatusFunctionArn}",
                  "Next": "WithUnderwriterMessage"
                },
                "WithUnderwriterMessage": {
                  "Type": "Task",
                  "Resource": "${CreateNotificationMessageFunctionArn}",
                  "Parameters": {
                    "messageType": "autoRejectionMessage",
                    "mortgage.$": "$.mortgage"
                  },
                  "ResultPath": "$.lambdaresult",
                  "Next": "WithUnderwriterNotify"
                },
                "WithUnderwriterNotify": {
                  "Type": "Task",
                  "InputPath": "$.lambdaresult",
                  "Resource": "${SendNotificationMessageFunctionArn}",
                  "ResultPath": "$.lambdaresult",
                  "Next": "AwaitUnderwriterDecision"
                },
                "AwaitUnderwriterDecision": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::lambda:invoke.waitForTaskToken",
                  "Parameters": {
                    "FunctionName": "${SendUnderwriterDecisionEmailArn}",
                    "Payload": {
                      "mortgage.$": "$.mortgage",
                      "ExecutionContext.$": "$$"
                    }
                  },
                  "TimeoutSeconds": 180,
                  "ResultPath": "$.lambdaresult",
                  "Next": "ProcessUnderwriterDecision"
                },
                "ProcessUnderwriterDecision": {
                  "Type": "Choice",
                  "Choices": [{
                    "Variable": "$.lambdaresult.statusCode",
                    "NumericEquals": 200,
                    "Next": "UpdateStatusToUnderwriterApproved"
                  }],
                  "Default": "UpdateStatusToUnderwriterRejected"
                },
                "UpdateStatusToUnderwriterApproved": {
                  "Type": "Task",
                  "Parameters": {
                    "mortgage.$": "$.mortgage",
                    "newStatus": "Approved"
                  },
                  "Resource": "${ChangeMortgageStatusFunctionArn}",
                  "Next": "UnderwriterApprovedMessage"
                },		
                "UnderwriterApprovedMessage": {
                  "Type": "Task",
                  "Resource": "${CreateNotificationMessageFunctionArn}",
                  "Parameters": {
                    "messageType": "underwriterApprovalMessage",
                    "mortgage.$": "$.mortgage"
                  },
                  "ResultPath": "$.lambdaresult",
                  "Next": "UnderwriterApprovedNotify"
                },
                "UnderwriterApprovedNotify": {
                  "Type": "Task",
                  "InputPath": "$.lambdaresult",
                  "Resource": "${SendNotificationMessageFunctionArn}",
                  "End": true
                },
                "UpdateStatusToUnderwriterRejected": {
                  "Type": "Task",
                  "Parameters": {
                    "mortgage.$": "$.mortgage",
                    "newStatus": "Rejected"
                  },
                  "Resource": "${ChangeMortgageStatusFunctionArn}",
                  "Next": "UnderwriterRejectedMessage"
                },
                "UnderwriterRejectedMessage": {
                  "Type": "Task",
                  "Resource": "${CreateNotificationMessageFunctionArn}",
                  "Parameters": {
                    "messageType": "underwriterRejectionMessage",
                    "mortgage.$": "$.mortgage"
                  },
                  "ResultPath": "$.lambdaresult",
                  "Next": "UnderwriterRejectedNotify"
                },
                "UnderwriterRejectedNotify": {
                  "Type": "Task",
                  "InputPath": "$.lambdaresult",
                  "Resource": "${SendNotificationMessageFunctionArn}",
                  "End": true
                }
              }
            }
          - {AutoAssessmentFunctionArn: !GetAtt [ AutoAssessmentFunction, Arn ]}
          - {CreateNotificationMessageFunctionArn: !GetAtt [ CreateNotificationMessageFunction, Arn ]}
          - {ChangeMortgageStatusFunctionArn: !GetAtt [ ChangeMortgageStatusFunction, Arn ]}
          - {GetMorgtageFunctionArn: !GetAtt [ WorkflowGetMorgtageFunction, Arn ]}
          - {SendNotificationMessageFunctionArn: !GetAtt [ SendNotificationMessageFunction, Arn ]}
          - {SendUnderwriterDecisionEmailArn: !GetAtt [ SendUnderwriterDecisionEmailFunction, Arn ]}