AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tallaght-Mortgages-App

Globals:
  Function:
    Timeout: 3
  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Parameters: 
  LambdaRoleParameter: 
    Type: String
    Default: "arn:aws:iam::727432808710:role/TUD.Mortgage.Lambda.Role"
    Description: Enter the ARN of an applicable IAM Role for the Lambda Functions
  StepFunctionArnParameter: 
    Type: String
    Default: "arn:aws:states:eu-west-1:727432808710:stateMachine:MortgageApprovalWorkflow"
    Description: Enter the ARN of the Workflow Step Function State Machine
  WebsocketConnectionTableName:
    Type: String
    Default: 'WEBSOCKET_CONNECTIONS_TABLE'

    
Resources:

  # SNS TOPICS
  UnderwriterSNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: UnderwriterSNSTopic
      Subscription: 
        - Endpoint: appduffin@gmail.com
          Protocol: email
      TopicName: UnderwriterSNSTopic
  BrokerSNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: BrokerSNSTopic
      Subscription: 
        - Endpoint: appduffin@gmail.com
          Protocol: email
      TopicName: BrokerSNSTopic

  # CUSTOMER APIS
  GetCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: customers/
      Handler: get.get
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        GetCustomerEvent:
          Type: Api
          Properties:
            Path: /customer/{id}
            Method: GET
  CreateCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: customers/
      Handler: create.create
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        CreateCustomerEvent:
          Type: Api
          Properties:
            Path: /customer/
            Method: PUT
  UpdateCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: customers/
      Handler: update.update
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        UpdateCustomerEvent:
          Type: Api
          Properties:
            Path: /customer/{id}
            Method: POST

  # MORTGAGE APIS
  GetMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mortgages/
      Handler: get.get
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        GetMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/{id}
            Method: GET
  CreateMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mortgages/
      Handler: create.create
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        CreateMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/
            Method: PUT
  UpdateMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mortgages/
      Handler: update.update
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        CreateMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/{id}
            Method: POST
  DeleteMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mortgages/
      Handler: delete.delete
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        DeleteMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/{id}
            Method: DELETE
  ListByStatusMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mortgages/
      Handler: list.list
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        ListByStatusMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/
            Method: GET

  # WORKFLOW APIS
  NofifyUsersSNSFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: stepfunctions/notifications/snsNotifications.handler
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Environment:
        Variables:
          UNDERWRITER_TOPIC_ARN: !Ref UnderwriterSNSTopic
          BROKER_TOPIC_ARN: !Ref BrokerSNSTopic
    DependsOn:
      - UnderwriterSNSTopic
      - BrokerSNSTopic

  WorkflowGetCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: stepfunctions/customers/findByPK.handler
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
  WorkflowGetMorgtageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: stepfunctions/mortgages/findByPK.handler
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
  WorkflowUpdateMorgtageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: stepfunctions/mortgages/updateMortgage.handler
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
  StartWorkflowFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: stepfunctions/startWorkflow.handler
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Environment:
        Variables:
          MORTGAGE_WORKFLOW_ARN: !Ref StepFunctionArnParameter
      Events:
        StartWorkflowEvent:
          Type: Api
          Properties:
            Path: /workflow/
            Method: POST
  AutoAssessmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: workflow/autoassessment.handler
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
  ChangeMortgageStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: stepfunctions/mortgages/changeMortgageStatus.handler
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
  MortgageStatusSNSFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: stepfunctions/notifications/mortgageStatusSend.handler
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter

  # WEBSOCKET APIS
  MortgageWebSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: MortgageWebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.message"
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref MortgageWebSocket
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref MortgateConnectionIntegration
  MortgateConnectionIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref MortgageWebSocket
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketConnectFunction.Arn}/invocations
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref MortgageWebSocket
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref MortgateDisconnectInteg
  MortgateDisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref MortgageWebSocket
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDisconnectFunction.Arn}/invocations
  SendRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref MortgageWebSocket
      RouteKey: sendmessage
      AuthorizationType: NONE
      OperationName: SendRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref SendInteg
  SendInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref MortgageWebSocket
      Description: Send Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketSendFunction.Arn}/invocations
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ConnectRoute
    - SendRoute
    - DisconnectRoute
    Properties:
      ApiId: !Ref MortgageWebSocket
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref MortgageWebSocket


  # WEBSOCKET DYNAMO DB TABLE
  WebsocketConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "connectionId"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "connectionId"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      TableName: !Ref WebsocketConnectionTableName

  # WEBSOCKET LAMBDA API
  WebSocketConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: websockets/onconnect/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME: !Ref WebsocketConnectionTableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref WebsocketConnectionTableName
  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - MortgageWebSocket
      - WebSocketConnectFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketConnectFunction
      Principal: apigateway.amazonaws.com
  WebSocketDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: websockets/ondisconnect/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME: !Ref WebsocketConnectionTableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref WebsocketConnectionTableName
  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - MortgageWebSocket
      - WebSocketDisconnectFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketDisconnectFunction
      Principal: apigateway.amazonaws.com
  WebSocketSendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: websockets/sendmessage/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME: !Ref WebsocketConnectionTableName
          WEBSOCKET_ENDPOINT: !Join [ '', [ !Ref MortgageWebSocket, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/Prod'] ]
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref WebsocketConnectionTableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MortgageWebSocket}/*'
  WebSocketSendPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - MortgageWebSocket
      - WebSocketSendFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketSendFunction
      Principal: apigateway.amazonaws.com


Outputs:
  MortgageApi:
    Description: "API Gateway endpoint URL for Prod stage for GetMortgageFunctionRole"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mortgage/"
  GetCustomerFunction:
    Description: "GetCustomerFunctionARN"
    Value: !GetAtt GetCustomerFunction.Arn
  CreateCustomerFunction:
    Description: "CreateCustomerFunctionARN"
    Value: !GetAtt CreateCustomerFunction.Arn
  UpdateCustomerFunction:
    Description: "UpdateCustomerFunctionARN"
    Value: !GetAtt UpdateCustomerFunction.Arn
#  GetMortgageFunction:
 #   Description: "GetMortgageFunctionARN"
#    Value: !GetAtt GetMortgageFunction.Arn
#  CreateMortgageFunction:
#    Description: "CreateMortgageFunctionARN"
 #   Value: !GetAtt CreateMortgageFunction.Arn
#  UpdateMortgageFunction:
 #   Description: "UpdateMortgageFunctionARN"
 #   Value: !GetAtt UpdateMortgageFunction.Arn
#  DeleteMortgageFunction:
#    Description: "DeleteMortgageFunctionARN"
 #   Value: !GetAtt DeleteMortgageFunction.Arn
#  ListByStatusMortgageFunction:
 #   Description: "ListByStatusMortgageFunctionARN"
 #   Value: !GetAtt ListByStatusMortgageFunction.Arn

  # WEBSOCKET OUTPUTS
  ConnectionsTableArn:
    Description: "Websocket Connections table ARN"
    Value: !GetAtt WebsocketConnectionsTable.Arn

  WebSocketConnectFunctionArn:
    Description: "Websocket OnConnect function ARN"
    Value: !GetAtt WebSocketConnectFunction.Arn

  WebSocketDisconnectFunctionArn:
    Description: "Websocket OnDisconnect function ARN"
    Value: !GetAtt WebSocketDisconnectFunction.Arn

  WebSocketSendFunctionArn:
    Description: "Websocket SendMessage function ARN"
    Value: !GetAtt WebSocketSendFunction.Arn

  WebSocketURI:
    Description: "Websocket WSS Protocol URI"
    Value: !Join [ '', [ 'wss://', !Ref MortgageWebSocket, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref 'Stage'] ]
