AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tallaght-Mortgages-App

Globals:
  Function:
    Timeout: 3

Parameters: 
  LambdaRoleParameter: 
    Type: String
    Default: "arn:aws:iam::727432808710:role/TUD.Mortgage.Lambda.Role"
    Description: Enter the ARN of an applicable IAM Role for the Lambda Functions

Resources:

  # CUSTOMER APIS
  GetCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: customers/
      Handler: get.get
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        GetCustomerEvent:
          Type: Api
          Properties:
            Path: /customer/{id}
            Method: GET
  CreateCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: customers/
      Handler: create.create
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        CreateCustomerEvent:
          Type: Api
          Properties:
            Path: /customer/
            Method: PUT
  UpdateCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: customers/
      Handler: update.update
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        UpdateCustomerEvent:
          Type: Api
          Properties:
            Path: /customer/
            Method: POST

  # MORTGAGE APIS
  GetMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mortgages/
      Handler: get.get
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        GetMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/{id}
            Method: GET
  CreateMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mortgages/
      Handler: create.create
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        CreateMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/
            Method: PUT
  UpdateMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mortgages/
      Handler: update.update
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        CreateMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/
            Method: POST
  DeleteMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mortgages/
      Handler: delete.delete
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        DeleteMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/{id}
            Method: DELETE
  ListByStatusMortgageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: mortgages/
      Handler: list.list
      Runtime: nodejs10.x
      Role: 
        Ref: LambdaRoleParameter
      Events:
        ListByStatusMortgageEvent:
          Type: Api
          Properties:
            Path: /mortgage/
            Method: GET


Outputs:
  MortgageApi:
    Description: "API Gateway endpoint URL for Prod stage for GetMortgageFunctionRole"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mortgage/"
  GetCustomerFunction:
    Description: "GetCustomerFunctionARN"
    Value: !GetAtt GetCustomerFunction.Arn
  CreateCustomerFunction:
    Description: "CreateCustomerFunctionARN"
    Value: !GetAtt CreateCustomerFunction.Arn
  UpdateCustomerFunction:
    Description: "UpdateCustomerFunctionARN"
    Value: !GetAtt UpdateCustomerFunction.Arn
#  GetMortgageFunction:
 #   Description: "GetMortgageFunctionARN"
#    Value: !GetAtt GetMortgageFunction.Arn
#  CreateMortgageFunction:
#    Description: "CreateMortgageFunctionARN"
 #   Value: !GetAtt CreateMortgageFunction.Arn
#  UpdateMortgageFunction:
 #   Description: "UpdateMortgageFunctionARN"
 #   Value: !GetAtt UpdateMortgageFunction.Arn
#  DeleteMortgageFunction:
#    Description: "DeleteMortgageFunctionARN"
 #   Value: !GetAtt DeleteMortgageFunction.Arn
#  ListByStatusMortgageFunction:
 #   Description: "ListByStatusMortgageFunctionARN"
 #   Value: !GetAtt ListByStatusMortgageFunction.Arn
